extends:
    - stylelint-config-recess-order

rules:
    at-rule-no-unknown: null
    block-no-empty: null
    custom-property-pattern: '[a-z0-9-]+'
    declaration-block-no-redundant-longhand-properties: null
    selector-class-pattern: '^([a-z][a-z0-9]*)((?:-|_|__)[a-z0-9]+)*$|^--.*$'
    selector-id-pattern: '^([a-z][a-z0-9]*)((?:-|_|__)[a-z0-9]+)*$|^--.*$'
    no-descending-specificity: null
    length-zero-no-unit: [true, { 'ignore': ['custom-properties'] }]
